I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 195, in script
    python:
  File "renpy/common/00start.rpy", line 196, in <module>
    renpy.execute_default_statement(True)
  File "game/catalogo_de_enemigos.rpy", line 48, in execute_default
    default enemigo_actual = cat_enemigos[lst_enemigo[indx_enemigo]]
  File "game/catalogo_de_enemigos.rpy", line 48, in <module>
    default enemigo_actual = cat_enemigos[lst_enemigo[indx_enemigo]]
NameError: name 'indx_enemigo' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 195, in script
    python:
  File "D:\Renpy\Renpy-8\renpy-8.3.4-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Renpy\Renpy-8\renpy-8.3.4-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 196, in <module>
    renpy.execute_default_statement(True)
  File "D:\Renpy\Renpy-8\renpy-8.3.4-sdk\renpy\exports\statementexports.py", line 372, in execute_default_statement
    i.execute_default(start)
  File "game/catalogo_de_enemigos.rpy", line 48, in execute_default
    default enemigo_actual = cat_enemigos[lst_enemigo[indx_enemigo]]
  File "D:\Renpy\Renpy-8\renpy-8.3.4-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/catalogo_de_enemigos.rpy", line 48, in <module>
    default enemigo_actual = cat_enemigos[lst_enemigo[indx_enemigo]]
NameError: name 'indx_enemigo' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.7.25031702
Screen examples 1.0
Thu Apr 17 00:05:06 2025
